name: manzoma
description: A Flutter SaaS application for attendance and payroll management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_search: ^6.0.2
  equatable: ^2.0.5
  flutter_localization: ^0.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.4
  go_router: ^12.1.1
  http: ^1.1.0
  intl: 0.19.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.0.0
  video_player: ^2.10.0
  gif_view: ^1.0.3
  image_sequence_animator: ^2.0.0
  timeago: ^3.7.1
  geolocator: ^14.0.2

dev_dependencies:
  build_runner: ^2.4.7

  # Linting
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/manzoma_animation/
    - assets/icons/
    - assets/videos/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
