// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqAHbe7k6V8tzPRr4Rq-sbvEpkEAPhIn8',
    appId: '1:573358136526:web:59d081f046d1e96807049f',
    messagingSenderId: '573358136526',
    projectId: 'hudor-2a83d',
    authDomain: 'hudor-2a83d.firebaseapp.com',
    storageBucket: 'hudor-2a83d.appspot.com',
    measurementId: 'G-W5TFBRE14H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE5LJdEIn322N4y4l1pCeeP4UygX_XaMU',
    appId: '1:573358136526:android:810e30f1447f89e207049f',
    messagingSenderId: '573358136526',
    projectId: 'hudor-2a83d',
    storageBucket: 'hudor-2a83d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiPXg3VPG6lCNh2IJ8Qy1FmC4Bo09gU68',
    appId: '1:573358136526:ios:6b16c492699b889107049f',
    messagingSenderId: '573358136526',
    projectId: 'hudor-2a83d',
    storageBucket: 'hudor-2a83d.appspot.com',
    iosBundleId: 'com.example.hudor',
  );
}
